runtime: php82

# Definovanie statických súborov (obrázky, CSS, JS), aby ich Google servoval rýchlo
handlers:
- url: /assets
  static_dir: assets

# Všetko ostatné smeruje na index.php (tvoj router)
- url: /.*
  script: index.php
